STATE_REGIONS = [
    {
        "basin": "Rhine",
        "code": "DE-BW",
        "federal_state": "Baden-Wurttemberg",
        "id": "baden-wurttemberg",
        "name": "Baden-Wurttemberg",
        "risk_profile": "stable",
        "sort_index": 10,
    },
    {
        "basin": "Danube",
        "code": "DE-BY",
        "federal_state": "Bavaria",
        "id": "bavaria",
        "name": "Bavaria",
        "risk_profile": "stable",
        "sort_index": 20,
    },
    {
        "basin": "Spree",
        "code": "DE-BE",
        "federal_state": "Berlin",
        "id": "berlin",
        "name": "Berlin",
        "risk_profile": "volatile",
        "sort_index": 30,
    },
    {
        "basin": "Oder",
        "code": "DE-BB",
        "federal_state": "Brandenburg",
        "id": "brandenburg",
        "name": "Brandenburg",
        "risk_profile": "volatile",
        "sort_index": 40,
    },
    {
        "basin": "Weser",
        "code": "DE-HB",
        "federal_state": "Bremen",
        "id": "bremen",
        "name": "Bremen",
        "risk_profile": "flood",
        "sort_index": 50,
    },
    {
        "basin": "Elbe",
        "code": "DE-HH",
        "federal_state": "Hamburg",
        "id": "hamburg",
        "name": "Hamburg",
        "risk_profile": "flood",
        "sort_index": 60,
    },
    {
        "basin": "Main",
        "code": "DE-HE",
        "federal_state": "Hesse",
        "id": "hesse",
        "name": "Hesse",
        "risk_profile": "stable",
        "sort_index": 70,
    },
    {
        "basin": "Weser",
        "code": "DE-NI",
        "federal_state": "Lower Saxony",
        "id": "lower-saxony",
        "name": "Lower Saxony",
        "risk_profile": "drying",
        "sort_index": 80,
    },
    {
        "basin": "Warnow",
        "code": "DE-MV",
        "federal_state": "Mecklenburg-Vorpommern",
        "id": "mecklenburg-vorpommern",
        "name": "Mecklenburg-Vorpommern",
        "risk_profile": "drying",
        "sort_index": 90,
    },
    {
        "basin": "Rhine",
        "code": "DE-NW",
        "federal_state": "North Rhine-Westphalia",
        "id": "north-rhine-westphalia",
        "name": "North Rhine-Westphalia",
        "risk_profile": "flood",
        "sort_index": 100,
    },
    {
        "basin": "Rhine",
        "code": "DE-RP",
        "federal_state": "Rhineland-Palatinate",
        "id": "rhineland-palatinate",
        "name": "Rhineland-Palatinate",
        "risk_profile": "volatile",
        "sort_index": 110,
    },
    {
        "basin": "Saar",
        "code": "DE-SL",
        "federal_state": "Saarland",
        "id": "saarland",
        "name": "Saarland",
        "risk_profile": "stable",
        "sort_index": 120,
    },
    {
        "basin": "Elbe",
        "code": "DE-SN",
        "federal_state": "Saxony",
        "id": "saxony",
        "name": "Saxony",
        "risk_profile": "volatile",
        "sort_index": 130,
    },
    {
        "basin": "Elbe",
        "code": "DE-ST",
        "federal_state": "Saxony-Anhalt",
        "id": "saxony-anhalt",
        "name": "Saxony-Anhalt",
        "risk_profile": "drying",
        "sort_index": 140,
    },
    {
        "basin": "Elbe",
        "code": "DE-SH",
        "federal_state": "Schleswig-Holstein",
        "id": "schleswig-holstein",
        "name": "Schleswig-Holstein",
        "risk_profile": "flood",
        "sort_index": 150,
    },
    {
        "basin": "Saale",
        "code": "DE-TH",
        "federal_state": "Thuringia",
        "id": "thuringia",
        "name": "Thuringia",
        "risk_profile": "stable",
        "sort_index": 160,
    },
]

STATE_READING_VALUES = {
    "baden-wurttemberg": (63, 24, 19, 385),
    "bavaria": (70, 24, 16, 418),
    "berlin": (52, 18, 22, 265),
    "brandenburg": (55, 16, 24, 294),
    "bremen": (62, 27, 18, 330),
    "hamburg": (67, 29, 17, 365),
    "hesse": (59, 21, 21, 342),
    "lower-saxony": (44, 12, 27, 258),
    "mecklenburg-vorpommern": (48, 14, 23, 238),
    "north-rhine-westphalia": (73, 34, 15, 503),
    "rhineland-palatinate": (69, 31, 18, 470),
    "saarland": (61, 25, 20, 352),
    "saxony": (66, 30, 17, 452),
    "saxony-anhalt": (57, 19, 23, 315),
    "schleswig-holstein": (64, 28, 16, 340),
    "thuringia": (58, 20, 22, 320),
}
